#!/usr/bin/env python3
"""Render deployment config from gpu-server/models.yaml (the source of truth).

Outputs (paths relative to the repo root):
  - gpu-server/models.generated.env   GPU_N_MODEL_* for the chat services
  - litellm/config.yaml                litellm/config.base.yaml + derived model_list
  - gpu-server/models.download.tsv     fetch list for scripts/download-models.sh
  - CLAUDE.md                          only the text between the
                                       <!-- BEGIN/END GENERATED: models|ports -->
                                       markers; the prose around them is untouched

Usage:
  render-config.py            validate the manifest and write the outputs
  render-config.py --check    validate and fail (exit 1) if any output is stale

Deterministic: the same manifest always renders byte-identical output, so the
committed files can be drift-checked in CI.
"""

import argparse
import difflib
import re
import sys
from pathlib import Path

import yaml

KINDS = {"chat", "text-embed", "vision-embed", "visual-embed", "image", "stt", "tts"}

# Chat templates we ship in gpu-server/chat-templates/. A chat model may pin one
# with `chat_template: <name>` in models.yaml; llama.cpp is then started with
# --chat-template-file instead of trusting whatever template the GGUF embeds.
# Several published GGUFs ship broken templates, so pinning is the safe default
# for any model whose prompt format matters.
CHAT_TEMPLATE_DIR = Path(__file__).resolve().parents[1] / "chat-templates"
# Path as seen from inside the container (see the compose bind mount).
CHAT_TEMPLATE_MOUNT = "/chat-templates"

REPO_ROOT = Path(__file__).resolve().parents[2]
MANIFEST = REPO_ROOT / "gpu-server" / "models.yaml"
BASE_CONFIG = REPO_ROOT / "litellm" / "config.base.yaml"
OUT_ENV = REPO_ROOT / "gpu-server" / "models.generated.env"
OUT_LITELLM = REPO_ROOT / "litellm" / "config.yaml"
OUT_DOWNLOAD = REPO_ROOT / "gpu-server" / "models.download.tsv"
OUT_CLAUDE = REPO_ROOT / "CLAUDE.md"

GENERATED_BANNER = "GENERATED by gpu-server/scripts/render-config.py from models.yaml — DO NOT EDIT."


class ManifestError(Exception):
    pass


def load_manifest() -> dict:
    data = yaml.safe_load(MANIFEST.read_text())
    if not isinstance(data, dict) or "models" not in data:
        raise ManifestError("models.yaml must be a mapping with a 'models' list")
    return data


def validate(manifest: dict) -> None:
    errors: list[str] = []
    if not manifest.get("host"):
        errors.append("missing top-level 'host'")

    seen_names: set[str] = set()
    seen_ports: dict[int, str] = {}
    for m in manifest.get("models", []):
        name = m.get("api_name", "<unnamed>")
        kind = m.get("kind")
        if kind not in KINDS:
            errors.append(f"{name}: kind '{kind}' not in {sorted(KINDS)}")
        if name in seen_names:
            errors.append(f"duplicate api_name '{name}'")
        seen_names.add(name)

        deployments = m.get("deployments") or []
        if not deployments:
            errors.append(f"{name}: no deployments")
        for d in deployments:
            gpu, port = d.get("gpu"), d.get("port")
            if not isinstance(gpu, int) or not (1 <= gpu <= 8):
                errors.append(f"{name}: gpu {gpu!r} out of range 1-8")
            if not isinstance(port, int):
                errors.append(f"{name}: port {port!r} is not an int")
            elif port in seen_ports:
                errors.append(
                    f"{name}: port {port} collides with {seen_ports[port]}"
                )
            else:
                seen_ports[port] = name

        # Capacity floor: dropping a routed replica (canary, maintenance) must be
        # a deliberate manifest edit that also lowers min_replicas with a dated
        # reason comment, never a silent side effect.
        min_replicas = m.get("min_replicas")
        if not isinstance(min_replicas, int) or isinstance(min_replicas, bool) or min_replicas < 1:
            errors.append(f"{name}: min_replicas must be an integer >= 1 (got {min_replicas!r})")
        elif len(deployments) < min_replicas:
            errors.append(
                f"{name}: {len(deployments)} routed deployment(s) is below "
                f"min_replicas {min_replicas}; if intentional, lower min_replicas "
                f"with a dated reason comment"
            )

        src = m.get("source") or {}
        if kind == "chat":
            if src.get("type") != "gguf" or not src.get("file"):
                errors.append(f"{name}: chat model must resolve to a gguf source")
            if not m.get("model_type"):
                errors.append(f"{name}: chat model missing model_type (sfw/nsfw)")

        docs = m.get("docs")
        if docs is not None and (
            not isinstance(docs, dict)
            or set(docs) - {"model", "quant"}
            or not all(isinstance(v, str) and v for v in docs.values())
        ):
            errors.append(f"{name}: docs must map 'model'/'quant' to non-empty strings")

        template = m.get("chat_template")
        if template is not None:
            if kind != "chat":
                errors.append(f"{name}: chat_template is only valid on kind: chat")
            elif not (CHAT_TEMPLATE_DIR / f"{template}.jinja").is_file():
                available = sorted(p.stem for p in CHAT_TEMPLATE_DIR.glob("*.jinja"))
                errors.append(
                    f"{name}: chat_template '{template}' not found in "
                    f"chat-templates/ (have: {available})"
                )

    if errors:
        raise ManifestError("invalid models.yaml:\n  - " + "\n  - ".join(errors))


def _dep_id(model: dict, index: int, deployment: dict) -> str:
    if model["kind"] == "chat":
        return f"heartcode-gpu{deployment['gpu']}"
    return f"{model['id_prefix']}{index + 1}"


def render_litellm(manifest: dict) -> str:
    base = yaml.safe_load(BASE_CONFIG.read_text())
    host = manifest["host"]

    model_list = []
    rate_limits = []
    aliases: dict[str, str] = {}
    for m in manifest["models"]:
        for i, d in enumerate(m["deployments"]):
            params = {
                "model": f"openai/{m['litellm_model']}",
                "api_base": f"http://{host}:{d['port']}/v1",
                "api_key": "sk-local",
            }
            params.update(m.get("params") or {})
            model_list.append(
                {
                    "model_name": m["api_name"],
                    "litellm_params": params,
                    "model_info": {"id": _dep_id(m, i, d), "mode": m["mode"]},
                }
            )
        if m.get("rate_limit"):
            rate_limits.append({"model_name": m["api_name"], **m["rate_limit"]})
        for alias in m.get("aliases") or []:
            aliases[alias] = m["api_name"]

    # Hand-maintained isolated evaluation routes (for example a canary model)
    # are kept outside the GPU manifest because they do not own a production
    # chat service or generated GPU_N_MODEL_* environment entry.
    model_list.extend(base.get("extra_model_list") or [])

    router = dict(base.get("router_settings") or {})
    if rate_limits:
        router["model_rate_limits"] = rate_limits
    if aliases:
        router["model_group_alias"] = aliases

    config = {"model_list": model_list, "router_settings": router}
    for key in ("general_settings", "litellm_settings"):
        if key in base:
            config[key] = base[key]

    body = yaml.safe_dump(config, sort_keys=False, default_flow_style=False, width=4096)
    return f"# {GENERATED_BANNER}\n# Edit gpu-server/models.yaml or litellm/config.base.yaml instead.\n{body}"


def render_env(manifest: dict) -> str:
    lines = [f"# {GENERATED_BANNER}", ""]
    for m in manifest["models"]:
        if m["kind"] != "chat":
            continue
        path = f"/models/{m['source']['file']}"
        template = m.get("chat_template")
        for d in m["deployments"]:
            gpu = d["gpu"]
            lines += [
                f"GPU_{gpu}_MODEL_TYPE={m['model_type']}",
                f"GPU_{gpu}_MODEL_PATH={path}",
                f"GPU_{gpu}_MODEL_NAME={m['env_model_name']}",
            ]
            # Empty when unpinned, so the wrapper falls back to the GGUF's own
            # embedded template and behaviour is unchanged.
            lines.append(
                f"GPU_{gpu}_CHAT_TEMPLATE="
                + (f"{CHAT_TEMPLATE_MOUNT}/{template}.jinja" if template else "")
            )
            lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def render_download(manifest: dict) -> str:
    lines = [f"# {GENERATED_BANNER}", "# columns: gguf<TAB>repo<TAB>file<TAB>fallback_file(-)  OR  snapshot<TAB>repo"]
    snapshots: list[str] = []
    for m in manifest["models"]:
        src = m.get("source") or {}
        if src.get("type") == "gguf":
            fallback = src.get("fallback_file", "-")
            lines.append(f"gguf\t{src['repo']}\t{src['file']}\t{fallback}")
        elif src.get("type") == "snapshot":
            for repo in src.get("repos") or []:
                if repo not in snapshots:
                    snapshots.append(repo)
    lines += [f"snapshot\t{repo}" for repo in snapshots]
    return "\n".join(lines) + "\n"


# --- CLAUDE.md topology tables ------------------------------------------------

DOC_BLOCKS = ("models", "ports")
DOC_NOTE = (
    "<!-- Generated by gpu-server/scripts/render-config.py from gpu-server/models.yaml. "
    "Do not edit by hand; `render-config.py --check` fails on drift. -->"
)

KIND_LABELS = {
    "text-embed": "Embedding (text)",
    "vision-embed": "Embedding (text + image)",
    "visual-embed": "Embedding (image-only)",
    "image": "Image",
    "stt": "Speech-to-text",
    "tts": "Text-to-speech",
}

# Quant tag inside a GGUF filename: ...-Q5_K_M.gguf, ...v1.5.Q8_0.gguf, ...-IQ4_XS-imat.gguf
GGUF_QUANT = re.compile(r"[-.](I?Q\d+(?:_[A-Z0-9]+)*|BF16|F16|F32)(?=[-.])")


def _spans(values: list[int]) -> str:
    """[1, 2, 3] -> '1-3'; [3, 6] -> '3, 6'; [1, 2, 4] -> '1-2, 4'."""
    values = sorted(values)
    parts: list[str] = []
    start = prev = values[0]
    for v in values[1:] + [None]:
        if v is not None and v == prev + 1:
            prev = v
            continue
        parts.append(str(start) if start == prev else f"{start}-{prev}")
        if v is not None:
            start = prev = v
    return ", ".join(parts)


def _doc_model(m: dict) -> str:
    return (m.get("docs") or {}).get("model") or m.get("env_model_name") or m["litellm_model"]


def _doc_quant(m: dict) -> str:
    quant = (m.get("docs") or {}).get("quant")
    if quant:
        return quant
    match = GGUF_QUANT.search((m.get("source") or {}).get("file", ""))
    return match.group(1) if match else "—"


def _doc_type(m: dict) -> str:
    if m["kind"] == "chat":
        return f"Chat ({m['model_type'].upper()})"
    return KIND_LABELS[m["kind"]]


def _doc_template(m: dict) -> str:
    if m["kind"] != "chat":
        return "—"
    template = m.get("chat_template")
    return f"`{template}` (pinned)" if template else "GGUF-embedded (`--jinja`)"


def render_doc_models(manifest: dict) -> str:
    lines = [
        "| API Name | Type | GPUs | Replicas (min) | Model | Quant | Chat Template |",
        "|----------|------|------|----------------|-------|-------|---------------|",
    ]
    aliases: dict[str, list[str]] = {}
    for m in manifest["models"]:
        gpus = _spans([d["gpu"] for d in m["deployments"]])
        replicas = f"{len(m['deployments'])} ({m['min_replicas']})"
        lines.append(
            f"| `{m['api_name']}` | {_doc_type(m)} | {gpus} | {replicas} | "
            f"{_doc_model(m)} | {_doc_quant(m)} | {_doc_template(m)} |"
        )
        if m.get("aliases"):
            aliases[m["api_name"]] = m["aliases"]
    if aliases:
        groups = " | ".join(
            ", ".join(f"`{a}`" for a in names) + f" → `{target}`"
            for target, names in aliases.items()
        )
        lines += ["", f"**Aliases**: {groups}"]
    return "\n".join(lines)


def render_doc_ports(manifest: dict) -> str:
    by_gpu: dict[int, list[str]] = {}
    for m in manifest["models"]:
        for d in m["deployments"]:
            by_gpu.setdefault(d["gpu"], []).append(m["api_name"])

    rows = []
    for m in manifest["models"]:
        gpus = [d["gpu"] for d in m["deployments"]]
        shared: dict[str, list[int]] = {}
        for gpu in gpus:
            for other in by_gpu[gpu]:
                if other != m["api_name"]:
                    shared.setdefault(other, []).append(gpu)
        shares = ", ".join(
            f"`{other}` (GPU {_spans(on)})" for other, on in shared.items()
        ) or "—"
        ports = [d["port"] for d in m["deployments"]]
        rows.append((min(ports), f"| {_spans(ports)} | `{m['api_name']}` | "
                                 f"{_doc_model(m)} | GPU {_spans(gpus)} | {shares} |"))

    lines = [
        "| Ports | Model group | Model | GPU | Shares GPU with |",
        "|-------|-------------|-------|-----|-----------------|",
    ]
    lines += [row for _, row in sorted(rows)]
    return "\n".join(lines)


def render_claude_md(manifest: dict, current: str) -> str:
    """Replace each GENERATED block in CLAUDE.md; leave every other byte alone."""
    markers = {
        name: (f"<!-- BEGIN GENERATED: {name} -->", f"<!-- END GENERATED: {name} -->")
        for name in DOC_BLOCKS
    }
    for begin, end in markers.values():
        if current.count(begin) != 1 or current.count(end) != 1 or current.index(begin) > current.index(end):
            raise ManifestError(f"CLAUDE.md must contain exactly one '{begin}' ... '{end}' block")

    bodies = {"models": render_doc_models(manifest), "ports": render_doc_ports(manifest)}
    out = current
    for name, (begin, end) in markers.items():
        head, rest = out.split(begin, 1)
        _, tail = rest.split(end, 1)
        out = f"{head}{begin}\n{DOC_NOTE}\n\n{bodies[name]}\n\n{end}{tail}"
    return out


def _rel(path: Path) -> Path:
    try:
        return path.relative_to(REPO_ROOT)
    except ValueError:
        return path


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if outputs are stale")
    args = parser.parse_args(argv)

    try:
        manifest = load_manifest()
        validate(manifest)
        targets = {
            OUT_ENV: render_env(manifest),
            OUT_LITELLM: render_litellm(manifest),
            OUT_DOWNLOAD: render_download(manifest),
            OUT_CLAUDE: render_claude_md(manifest, OUT_CLAUDE.read_text()),
        }
    except (ManifestError, yaml.YAMLError) as exc:
        print(f"manifest validation failed:\n{exc}", file=sys.stderr)
        return 1

    if args.check:
        stale = False
        for path, rendered in targets.items():
            current = path.read_text() if path.exists() else ""
            if current != rendered:
                stale = True
                rel = _rel(path)
                print(f"DRIFT: {rel} is out of sync with models.yaml", file=sys.stderr)
                diff = difflib.unified_diff(
                    current.splitlines(), rendered.splitlines(),
                    fromfile=f"{rel} (committed)", tofile=f"{rel} (regenerated)", lineterm="",
                )
                print("\n".join(diff), file=sys.stderr)
        if stale:
            print("\nRun: python3 gpu-server/scripts/render-config.py", file=sys.stderr)
            return 1
        print("OK: all generated files are in sync with models.yaml")
        return 0

    for path, rendered in targets.items():
        path.write_text(rendered)
        print(f"wrote {_rel(path)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
