#!/usr/bin/env python3
"""Render deployment config from gpu-server/models.yaml (the source of truth).

Outputs (paths relative to the repo root):
  - gpu-server/models.generated.env   GPU_N_MODEL_* for the chat services
  - litellm/config.yaml                litellm/config.base.yaml + derived model_list
  - gpu-server/models.download.tsv     fetch list for scripts/download-models.sh

Usage:
  render-config.py            validate the manifest and write the outputs
  render-config.py --check    validate and fail (exit 1) if any output is stale

Deterministic: the same manifest always renders byte-identical output, so the
committed files can be drift-checked in CI.
"""

import argparse
import difflib
import sys
from pathlib import Path

import yaml

KINDS = {"chat", "text-embed", "vision-embed", "visual-embed", "image"}

REPO_ROOT = Path(__file__).resolve().parents[2]
MANIFEST = REPO_ROOT / "gpu-server" / "models.yaml"
BASE_CONFIG = REPO_ROOT / "litellm" / "config.base.yaml"
OUT_ENV = REPO_ROOT / "gpu-server" / "models.generated.env"
OUT_LITELLM = REPO_ROOT / "litellm" / "config.yaml"
OUT_DOWNLOAD = REPO_ROOT / "gpu-server" / "models.download.tsv"

GENERATED_BANNER = "GENERATED by gpu-server/scripts/render-config.py from models.yaml — DO NOT EDIT."


class ManifestError(Exception):
    pass


def load_manifest() -> dict:
    data = yaml.safe_load(MANIFEST.read_text())
    if not isinstance(data, dict) or "models" not in data:
        raise ManifestError("models.yaml must be a mapping with a 'models' list")
    return data


def validate(manifest: dict) -> None:
    errors: list[str] = []
    if not manifest.get("host"):
        errors.append("missing top-level 'host'")

    seen_names: set[str] = set()
    seen_ports: dict[int, str] = {}
    for m in manifest.get("models", []):
        name = m.get("api_name", "<unnamed>")
        kind = m.get("kind")
        if kind not in KINDS:
            errors.append(f"{name}: kind '{kind}' not in {sorted(KINDS)}")
        if name in seen_names:
            errors.append(f"duplicate api_name '{name}'")
        seen_names.add(name)

        deployments = m.get("deployments") or []
        if not deployments:
            errors.append(f"{name}: no deployments")
        for d in deployments:
            gpu, port = d.get("gpu"), d.get("port")
            if not isinstance(gpu, int) or not (1 <= gpu <= 8):
                errors.append(f"{name}: gpu {gpu!r} out of range 1-8")
            if not isinstance(port, int):
                errors.append(f"{name}: port {port!r} is not an int")
            elif port in seen_ports:
                errors.append(
                    f"{name}: port {port} collides with {seen_ports[port]}"
                )
            else:
                seen_ports[port] = name

        src = m.get("source") or {}
        if kind == "chat":
            if src.get("type") != "gguf" or not src.get("file"):
                errors.append(f"{name}: chat model must resolve to a gguf source")
            if not m.get("model_type"):
                errors.append(f"{name}: chat model missing model_type (sfw/nsfw)")

    if errors:
        raise ManifestError("invalid models.yaml:\n  - " + "\n  - ".join(errors))


def _dep_id(model: dict, index: int, deployment: dict) -> str:
    if model["kind"] == "chat":
        return f"heartcode-gpu{deployment['gpu']}"
    return f"{model['id_prefix']}{index + 1}"


def render_litellm(manifest: dict) -> str:
    base = yaml.safe_load(BASE_CONFIG.read_text())
    host = manifest["host"]

    model_list = []
    rate_limits = []
    aliases: dict[str, str] = {}
    for m in manifest["models"]:
        for i, d in enumerate(m["deployments"]):
            params = {
                "model": f"openai/{m['litellm_model']}",
                "api_base": f"http://{host}:{d['port']}/v1",
                "api_key": "sk-local",
            }
            params.update(m.get("params") or {})
            model_list.append(
                {
                    "model_name": m["api_name"],
                    "litellm_params": params,
                    "model_info": {"id": _dep_id(m, i, d), "mode": m["mode"]},
                }
            )
        if m.get("rate_limit"):
            rate_limits.append({"model_name": m["api_name"], **m["rate_limit"]})
        for alias in m.get("aliases") or []:
            aliases[alias] = m["api_name"]

    router = dict(base.get("router_settings") or {})
    if rate_limits:
        router["model_rate_limits"] = rate_limits
    if aliases:
        router["model_group_alias"] = aliases

    config = {"model_list": model_list, "router_settings": router}
    for key in ("general_settings", "litellm_settings"):
        if key in base:
            config[key] = base[key]

    body = yaml.safe_dump(config, sort_keys=False, default_flow_style=False, width=4096)
    return f"# {GENERATED_BANNER}\n# Edit gpu-server/models.yaml or litellm/config.base.yaml instead.\n{body}"


def render_env(manifest: dict) -> str:
    lines = [f"# {GENERATED_BANNER}", ""]
    for m in manifest["models"]:
        if m["kind"] != "chat":
            continue
        path = f"/models/{m['source']['file']}"
        for d in m["deployments"]:
            gpu = d["gpu"]
            lines += [
                f"GPU_{gpu}_MODEL_TYPE={m['model_type']}",
                f"GPU_{gpu}_MODEL_PATH={path}",
                f"GPU_{gpu}_MODEL_NAME={m['env_model_name']}",
                "",
            ]
    return "\n".join(lines).rstrip("\n") + "\n"


def render_download(manifest: dict) -> str:
    lines = [f"# {GENERATED_BANNER}", "# columns: gguf<TAB>repo<TAB>file<TAB>fallback_file(-)  OR  snapshot<TAB>repo"]
    snapshots: list[str] = []
    for m in manifest["models"]:
        src = m.get("source") or {}
        if src.get("type") == "gguf":
            fallback = src.get("fallback_file", "-")
            lines.append(f"gguf\t{src['repo']}\t{src['file']}\t{fallback}")
        elif src.get("type") == "snapshot":
            for repo in src.get("repos") or []:
                if repo not in snapshots:
                    snapshots.append(repo)
    lines += [f"snapshot\t{repo}" for repo in snapshots]
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if outputs are stale")
    args = parser.parse_args(argv)

    try:
        manifest = load_manifest()
        validate(manifest)
    except (ManifestError, yaml.YAMLError) as exc:
        print(f"manifest validation failed:\n{exc}", file=sys.stderr)
        return 1

    targets = {
        OUT_ENV: render_env(manifest),
        OUT_LITELLM: render_litellm(manifest),
        OUT_DOWNLOAD: render_download(manifest),
    }

    if args.check:
        stale = False
        for path, rendered in targets.items():
            current = path.read_text() if path.exists() else ""
            if current != rendered:
                stale = True
                rel = path.relative_to(REPO_ROOT)
                print(f"DRIFT: {rel} is out of sync with models.yaml", file=sys.stderr)
                diff = difflib.unified_diff(
                    current.splitlines(), rendered.splitlines(),
                    fromfile=f"{rel} (committed)", tofile=f"{rel} (regenerated)", lineterm="",
                )
                print("\n".join(diff), file=sys.stderr)
        if stale:
            print("\nRun: python3 gpu-server/scripts/render-config.py", file=sys.stderr)
            return 1
        print("OK: all generated files are in sync with models.yaml")
        return 0

    for path, rendered in targets.items():
        path.write_text(rendered)
        print(f"wrote {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
